on: [push]

jobs:
    appium_job:
        runs-on: ubuntu-latest
        name: Run Appium Test
        steps:
        - name: Appium Test step
          id: Appium
          uses: Zemotacqy/Appium-js@v1.2
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BS_USERNAME: ${{ secrets.BS_USERNAME }}
            BS_ACCESSKEY: ${{ secrets.BS_ACCESSKEY }}  
